services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./app/db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    container_name: fastapi
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  
  frontend:
    build:
      context: ./chat-ui
      dockerfile: Dockerfile
    container_name: react
    environment:
      CHAT_SERVER_URL: http://backend:8000
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: